# Generated by Django 5.1.1 on 2025-02-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_oldcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='oldcart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
